// Proof of provenance: every UI piece of the lab, the 21st.dev component it comes from, and what changed.
// This file renders the "Sources 21st" screen and generates ui-lab/21st-manifest.md (npm run manifest).
export const MANIFEST = [
  { piece: 'Sidebar / navigation', name: 'Sidebar', author: 'wensity', demo: 31454, url: 'https://21st.dev/@wensity/components/sidebar', file: 'src/components/21st/sidebar.tsx', screens: 'Toutes les pages apprenant, formateur, institution', changes: 'Aucun (jetons via theme.css ; chemins d’import).', deps: '@base-ui/react, @tabler/icons-react, framer-motion, clsx, tailwind-merge' },
  { piece: 'Drawer (menu mobile, confirmations, invitation)', name: 'Drawer', author: 'wensity', demo: 31360, url: 'https://21st.dev/@wensity/components/drawer', file: 'src/components/21st/drawer.tsx', screens: 'Barre mobile (toutes pages), Réglages, Invitations, Séance', changes: 'Copie FR (libellé de fermeture, titre de secours).', deps: '@base-ui/react, @tabler/icons-react' },
  { piece: 'Command menu (⌘K)', name: 'Command Menu', author: 'uvain', demo: 33510, url: 'https://21st.dev/@uvain/components/command-menu-palette', file: 'src/components/21st/command-menu.tsx', screens: 'Global (palette ⌘K / Ctrl K, barre Labo, topbar mobile)', changes: 'Copie FR (placeholder, vide, pied).', deps: 'cmdk, @radix-ui/react-dialog' },
  { piece: 'Hero (entrée, portrait)', name: 'Hero 115', author: 'shadcnblockscom', demo: 608, url: 'https://21st.dev/@shadcnblockscom/components/shadcnblocks-com-hero115', file: 'src/components/21st/hero-115.tsx', screens: 'Accueil, Invitation, Mon portrait, Premium', changes: 'Aucun (texte et image passés en props).', deps: '@radix-ui/react-slot, class-variance-authority' },
  { piece: 'Readiness ring / gauge', name: 'Circular Progress with Custom Color', author: 'shadcnui-blocks', demo: 22095, url: 'https://21st.dev/@shadcnui-blocks/components/progress-10', file: 'src/components/21st/circular-progress.tsx', screens: 'Ma préparation, Fin de séance, Portrait, Cockpit', changes: 'Aucun (couleur de palier via progressClassName).', deps: '—' },
  { piece: 'Cards (KPI)', name: 'Stats Card', author: 'ravikatiyar162', demo: 8321, url: 'https://21st.dev/@ravikatiyar162/components/stats-card-1', file: 'src/components/21st/stats-card.tsx', screens: 'Ma préparation, Cockpit, Institution, Laboratoire', changes: 'Copie FR : « from last month » → prop changeNote ; emerald → jeton tier-3.', deps: '— (Card du registre shadcn)' },
  { piece: 'Cards (contenu)', name: 'Card (registre shadcn livré avec Stats Card / Carousel)', author: 'shadcn', demo: 8321, url: 'https://21st.dev/@shadcn/components/card', file: 'src/components/ui/card.tsx', screens: 'Toutes', changes: 'CardTitle h3 → div (comme shadcn actuel) : les écrans posent eux-mêmes h1/h2.', deps: '—' },
  { piece: 'Progress (domaines, séance)', name: 'Progress', author: 'jshguo', demo: 11889, url: 'https://21st.dev/@jshguo/components/interfaces-progress', file: 'src/components/21st/progress.tsx', screens: 'Séance, Parcours, Portrait, Réglages', changes: 'Aucun.', deps: '@radix-ui/react-progress' },
  { piece: 'Progress par compétence', name: 'Skills Progress Dashboard', author: 'shadcnspace', demo: 19138, url: 'https://21st.dev/@shadcnspace/components/progress-03', file: 'src/components/21st/skills-progress.tsx', screens: 'Ma préparation, Portrait, Cockpit', changes: 'Copie FR ; tableau codé en dur → prop stats (même forme) ; slot progress-track → progress (Progress jshguo) ; aria-label sur chaque barre ; badge teal → jetons palier.', deps: 'class-variance-authority (Badge)' },
  { piece: 'Tabs', name: 'Animated Tabs', author: 'educalvolpz', demo: 24930, url: 'https://21st.dev/@educalvolpz/components/animated-tabs', file: 'src/components/21st/animated-tabs.tsx', screens: 'Barre d’onglets mobile, Cockpit, Carte mentale, Parcours, Chat', changes: 'Aucun (jeton --color-brand défini).', deps: 'motion' },
  { piece: 'Accordion', name: 'Basic Accordion', author: 'felipemenezes098', demo: 24849, url: 'https://21st.dev/@felipemenezes098/components/accordion-01', file: 'src/components/21st/accordion.tsx', screens: 'Ma préparation (questions manquées), Parcours, Réglages, Premium, Sources', changes: 'Copie FR ; 3 items codés en dur → prop items (même balisage).', deps: '@radix-ui/react-accordion, lucide-react' },
  { piece: 'Popover', name: 'Popover', author: 'originui', demo: 403, url: 'https://21st.dev/@originui/components/popover', file: 'src/components/21st/popover.tsx', screens: 'Ma préparation (paliers), Carte mentale, Cockpit', changes: 'Aucun.', deps: '@radix-ui/react-popover' },
  { piece: 'Chat input', name: 'Prompt Input', author: 'tinkerers-labs', demo: 31882, url: 'https://21st.dev/@tinkerers-labs/components/prompt-input', file: 'src/components/21st/prompt-input.tsx', screens: 'Expliquer, Cas d’examen, Relier, Cas réel', changes: 'Copie FR (placeholder, libellés).', deps: '—' },
  { piece: 'Quiz options', name: 'Question Tool', author: 'serafimcloud', demo: 12421, url: 'https://21st.dev/@serafimcloud/components/question-tool', file: 'src/components/21st/question-tool.tsx', screens: 'Lecteur de séance, Me tester, Composer une séance', changes: 'Copie FR (libellés, placeholders, aria) ; jetons (palette neutral → jetons Certifizer).', deps: 'clsx, tailwind-merge' },
  { piece: 'Progress / stepper', name: 'Vertical Titled Stepper', author: 'sean0205', demo: 29815, url: 'https://21st.dev/@sean0205/components/c-stepper-15', file: 'src/components/21st/vertical-stepper.tsx', screens: 'Chemin critique, Email de récupération, Lien magique', changes: 'Copie FR ; étapes codées en dur → props steps/value ; stepper.tsx du registre : rôles tablist/tab (invalides pour axe, les items enveloppent les déclencheurs) → group + aria-current.', deps: 'radix-ui, lucide-react, class-variance-authority' },
  { piece: 'Timeline', name: 'Process Timeline', author: 'shadcnui-blocks', demo: 28381, url: 'https://21st.dev/@shadcnui-blocks/components/timeline-05', file: 'src/components/21st/process-timeline.tsx', screens: 'Parcours ECO, Relier à mon projet (livrables), Réglages (délai de grâce)', changes: 'Copie FR ; étapes codées en dur → prop steps.', deps: 'lucide-react' },
  { piece: 'Chart — radar', name: 'Radar Chart', author: 'heygaia', demo: 29830, url: 'https://21st.dev/@heygaia/components/radar-chart', file: 'src/components/21st/radar-chart.tsx', screens: 'Mon portrait, Cockpit', changes: 'Jetons (palette → couleurs des domaines ECO).', deps: 'recharts' },
  { piece: 'Chart — courbe', name: 'Line Chart', author: 'heygaia', demo: 29015, url: 'https://21st.dev/@heygaia/components/line-chart', file: 'src/components/21st/line-chart.tsx', screens: 'Mon portrait (trajectoire), Cockpit, Institution', changes: 'Jetons (palette → couleurs des domaines ECO).', deps: 'recharts' },
  { piece: 'Heatmap', name: 'Heat Calendar', author: 'ssychui', demo: 30542, url: 'https://21st.dev/@ssychui/components/heat-calendar', file: 'src/components/21st/heat-calendar.tsx', screens: 'Mon portrait (activité), Cockpit (heatmap)', changes: 'Copie FR (jours, aria-label).', deps: 'framer-motion' },
  { piece: 'Chart — anneau', name: 'Chart Donut Halftone', author: 'nikolas-sapa', demo: 32787, url: 'https://21st.dev/@nikolas-sapa/components/chart-donut-halftone', file: 'src/components/21st/donut-halftone.tsx', screens: 'Fin de séance, Cockpit (groupes), Institution', changes: 'Copie FR (titre par défaut, aria-label).', deps: '—' },
  { piece: 'Data table', name: 'Data Table', author: 'ephraimduncan', demo: 28327, url: 'https://21st.dev/@ephraimduncan/components/table-05', file: 'src/components/21st/data-table.tsx', screens: 'Sources 21st, Cockpit (cohorte, qualité), Invitations, Institution', changes: 'Copie FR ; colonnes/données → props (défauts = celles de la démo) ; couleurs de statut → jetons de palier ; trigger render= → asChild (radix) ; aria-label sur le sélecteur de taille de page.', deps: '@tanstack/react-table, @radix-ui/react-checkbox, @radix-ui/react-dropdown-menu, @radix-ui/react-select' },
  { piece: 'Constellation / graph', name: 'Knowledge Graph', author: 'heygaia', demo: 31573, url: 'https://21st.dev/@heygaia/components/knowledge-graph', file: 'src/components/21st/knowledge-graph.tsx', screens: 'Carte mentale (26 tâches), Cockpit (constellation)', changes: 'Jetons (surfaces zinc, légende, liens → jetons Certifizer) ; la légende prend la couleur du nœud ; libellés de type laissés en français.', deps: 'd3' },
  { piece: 'Arbre (13 thèmes)', name: 'Branching Tree Nav', author: 'arunachalam', demo: 25276, url: 'https://21st.dev/@arunachalam/components/branching-tree-nav', file: 'src/components/21st/branching-tree-nav.tsx', screens: 'Carte mentale (arbre), Parcours ECO, Me tester', changes: 'Jetons (badge bleu → accent) ; a11y : racine nav→div, en-têtes de section = treeitem, contenu replié = group + inert.', deps: 'framer-motion, lucide-react' },
  { piece: 'Empty state', name: 'Empty State', author: 'serafimcloud', demo: 1435, url: 'https://21st.dev/@serafimcloud/components/empty-state', file: 'src/components/21st/empty-state.tsx', screens: 'Portrait vide, Cohorte vide, Invitations vides, Me tester, Composer', changes: 'Aucun.', deps: '@radix-ui/react-slot' },
  { piece: 'Loading state', name: 'Skeleton', author: 'shadcn', demo: 1588, url: 'https://21st.dev/@shadcn/components/skeleton', file: 'src/components/21st/skeleton.tsx', screens: 'Tous les états « Chargement »', changes: 'Aucun.', deps: '—' },
  { piece: 'Error state', name: 'Alert', author: 'shadcn', demo: 1170, url: 'https://21st.dev/@shadcn/components/alert', file: 'src/components/21st/alert.tsx', screens: 'Tous les états « Erreur », Accès, Réglages', changes: 'Aucun.', deps: 'class-variance-authority' },
  { piece: 'Toasts', name: 'Sonner Toast', author: 'isaiahbjork', demo: 27363, url: 'https://21st.dev/@isaiahbjork/components/primitive-sonner', file: 'src/components/21st/sonner-toast.tsx', screens: 'Global ; Réglages, Invitations, Séance', changes: 'Copie FR ; BjorkButton (non livré) → Button du registre ; prop showButton ; jetons bjork-* aliasés.', deps: 'sonner, next-themes' },
  { piece: 'Language switch / segmented', name: 'Segmented Control', author: 'ddoemonn', demo: 23552, url: 'https://21st.dev/@ddoemonn/components/segmented-control', file: 'src/components/21st/segmented-control.tsx', screens: 'Réglages (FR/EN), Barre Labo (direction), Me tester, Carte mentale', changes: 'Aucun.', deps: 'motion' },
  { piece: 'Switch', name: 'Switch', author: 'jshguo', demo: 11886, url: 'https://21st.dev/@jshguo/components/interfaces-switch', file: 'src/components/21st/switch.tsx', screens: 'Barre Labo (réduire les animations), Réglages', changes: 'Aucun.', deps: '@radix-ui/react-switch' },
  { piece: 'Carousel', name: 'Carousel', author: 'shadcn', demo: 813, url: 'https://21st.dev/@shadcn/components/carousel', file: 'src/components/21st/carousel.tsx', screens: 'Laboratoire (directions), Premium, Ma préparation (réflexes)', changes: 'Copie FR (libellés sr-only).', deps: 'embla-carousel-react' },
  { piece: 'Scroll reveal', name: 'Scroll Reveal', author: 'cnippet-dev', demo: 18654, url: 'https://21st.dev/@cnippet-dev/components/scroll-reveal-2', file: 'src/components/21st/scroll-reveal.tsx', screens: 'Laboratoire, Ma préparation, Portrait, Premium', changes: 'Aucun.', deps: 'motion' },
  { piece: 'Boutons, badges, champs, select, tableau, menu', name: 'Registre shadcn livré par 21st avec les démos ci-dessus', author: 'shadcn', demo: 28327, url: 'https://21st.dev/@shadcn', file: 'src/components/ui/*.tsx', screens: 'Toutes', changes: 'Aucun, sauf table.tsx : conteneur défilant focalisable (tabIndex, role=region).', deps: '—' },
]

// Fetched from 21st but not usable as shipped (missing helper files in the registry payload) — and what replaced them.
export const NOT_USABLE = [
  { name: 'Animated Sidebar', author: 'starc007', demo: 29334, why: 'Dépend de shared-layout-bg / ease non livrés.', replaced: 'Sidebar (wensity, 31454)' },
  { name: 'Choicebox', author: 'halaska-studio', demo: 34718, why: 'Dépend de kit-theme (halaska) non livré.', replaced: 'Question Tool (serafimcloud, 12421)' },
  { name: 'Switch', author: 'halaska-studio', demo: 34784, why: 'Dépend de kit-theme (halaska) non livré.', replaced: 'Switch (jshguo, 11886)' },
  { name: 'Progress Metric Card', author: 'makviesainte', demo: 15024, why: 'Dépend de metric-chart / controls non livrés.', replaced: 'Stats Card (8321) + Skills Progress (19138)' },
  { name: 'Sheet (Different Directions)', author: 'shadcnspace', demo: 25002, why: 'Dépend de sheet-01-utils/sheet non livré.', replaced: 'Drawer (wensity, 31360)' },
  { name: 'Questionnaire', author: 'uiable', demo: 28569, why: 'Dépend de @shadcn/react/questionnaire non livré.', replaced: 'Question Tool (serafimcloud, 12421)' },
]

// Hand-built, because 21st has nothing usable for them (kept deliberately tiny).
export const HAND_BUILT = [
  { piece: 'Voile Premium (flou léger + étiquette)', file: 'src/screens/_shared.jsx', why: 'Motif produit Certifizer (contenu réel visible, jamais un écran verrouillé) ; aucun composant 21st ne fait ce voile.' },
  { piece: 'Grille de page, barre « Labo » et chrome du laboratoire', file: 'src/styles/lab.css, src/App.jsx', why: 'Outillage du laboratoire, pas un composant produit.' },
  { piece: 'Photos Unsplash (accueil, portrait)', file: 'src/screens/Acces.jsx, src/screens/Portrait.jsx', why: 'images.unsplash.com et cdn.21st.dev restent refusés par le proxy réseau (CONNECT 403) : emplacements et textes alternatifs en place, image à insérer.' },
]

// Direction « Chantier » (chantier.html): the six scroll effects of the story page, fetched with get_component and
// adapted from the real code to GSAP ScrollTrigger + Lenis (the design system's motion stack).
export const CHANTIER = [
  { piece: 'Barre de progression de lecture', name: 'Scroll Progress', author: 'cnippet-dev', demo: 18715, url: 'https://21st.dev/@cnippet-dev/components/scroll-progress', file: 'src/chantier/components/21st/ScrollProgress.jsx', screens: 'Accueil (récit)', changes: 'useScroll + useSpring(damping 50, stiffness 200) → ScrollTrigger start 0 / end max + gsap.quickTo(0,5 s, power3.out) pour suivre Lenis ; classes Tailwind → .progress ; masquée en mouvement réduit.' },
  { piece: 'Apparition au défilement (titres, CTA, cohorte)', name: 'Reveal', author: 'asanshay', demo: 19240, url: 'https://21st.dev/@asanshay/components/reveal', file: 'src/chantier/components/21st/Reveal.jsx', screens: 'Accueil (récit) : « Pour qui », « Pour les formateurs », appel final', changes: 'Mêmes valeurs (opacity 0 → 1, y 40 → 0, blur 10 px → 0, 0,6 s, délai index × 0,15 s, une seule fois) sur un ScrollTrigger « top 80% » ; prop `as` ; état final en mouvement réduit.' },
  { piece: 'Film qui grandit au défilement', name: 'Video Scroll Hero', author: 'isaiahbjork', demo: 7512, url: 'https://21st.dev/@isaiahbjork/components/video-scroll-hero', file: 'src/chantier/components/21st/VideoScrollHero.jsx', screens: 'Accueil (récit) : film site.mp4 après le hero', changes: 'Conteneur 200vh + scène sticky conservés ; le listener scroll (scale = 0,25 + progress × 0,75) → ScrollTrigger scrub 0,8 ; <video autoplay> → <Film> (muet, en boucle, poster, pause hors écran, poster seul en mouvement réduit) ; légende en slot ; Tailwind → .vsh.' },
  { piece: 'Livrables qui défilent à l’horizontale', name: 'Horizontal Scroll Gallery', author: 'pulkitxm', demo: 20139, url: 'https://21st.dev/@pulkitxm/components/horizontal-scroll-gallery', file: 'src/chantier/components/21st/HorizontalScrollGallery.jsx', screens: 'Accueil (récit) : « Réviser en produisant du vrai travail »', changes: 'Enveloppe 300 % + zone sticky conservées ; le listener scroll (translateX = −progress × (largeur piste − viewport)) → ScrollTrigger scrub 0,6 avec invalidateOnRefresh, exposé en containerAnimation aux cartes ; slot `intro` au-dessus de la piste ; défilement latéral natif en mouvement réduit.' },
  { piece: 'Photos qui s’ouvrent (masque)', name: 'Reveal Image Mask', author: 'daiwiikharihar', demo: 10905, url: 'https://21st.dev/@daiwiikharihar/components/reveal-image-mask', file: 'src/chantier/components/21st/RevealImageMask.jsx', screens: 'Accueil (récit) : « Pour qui » (3 photos)', changes: 'Même interpolation clip-path (rounded : inset 30 % → 0, rayon 10 % → 0 ; circle : 16 % → 75 %) et mêmes bornes (start 85 % / end 15 %) ; useSpring(170/24) → scrub 0,8 ; le bloc titre/légende devient un <figcaption> ; Tailwind → .person.' },
  { piece: 'Photo qui s’élargit au défilement', name: 'Scroll Reveal Image', author: 'unlumen', demo: 24466, url: 'https://21st.dev/@unlumen/components/scroll-reveal-image', file: 'src/chantier/components/21st/ScrollRevealImage.jsx', screens: 'Accueil (récit) : photo formatrice', changes: 'Trois pistes conservées (largeur 40 % → 100 %, échelle 1,6 → 1, rayon 0 → 22 px à partir de 0,5) sur un seul ScrollTrigger scrub 1 (≈ le ressort 120/80), mêmes bornes « start end » → « start start » ; next/image → <img> ; état final en mouvement réduit.' },
]
